language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-24.0.2
    - android-24
    - extra-android-m2repository
    - extra-google-m2repository

env:
  global:
    - ARTEFACT=build-$TRAVIS_BUILD_NUMBER-$TRAVIS_BRANCH-$TRAVIS_COMMIT
  matrix:
    - BUILD=assembleDebug
    - BUILD=assembleRelease

before_script:
  - gem install supply

script:
   - ./gradlew $BUILD

deploy:
  provider: s3
  access_key_id: "YOUR AWS ACCESS KEY"
  secret_access_key: "YOUR AWS SECRET KEY"
  bucket: "dvorac-android-buildtest-builds"
  skip_cleanup: true
  local_dir: build