language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-24.0.2
    - android-24
    - extra-android-m2repository
    - extra-google-m2repository

env:
  global:
    - TAG=$TRAVIS_BUILD_NUMBER-$TRAVIS_BRANCH-$TRAVIS_COMMIT
  matrix:
    - BUILD=assembleDev S3_DIR=dev-$TAG
    - BUILD=assembleRelease S3_DIR=prod-$TAG

before_install:
  - openssl aes-256-cbc -K $encrypted_11c483ba8457_key -iv $encrypted_11c483ba8457_iv -in ci/dev.jks.enc -out dev.jks -d
  - openssl aes-256-cbc -K $encrypted_11c483ba8457_key -iv $encrypted_11c483ba8457_iv -in ci/release.jks.enc -out release.jks -d
#  - openssl aes-256-cbc -K $encrypted_11c483ba8457_key -iv $encrypted_11c483ba8457_iv -in ./ci/playstore-publish-credentials.json.enc -out playstore-publish-credentials.json -d

#install:
#  - gem install supply

before_script:
  - chmod +x ./gradlew

script:
  - ./gradlew $BUILD

#after_success:
#  - supply init --json_key playstore-publish-credentials.json --package com.

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_ACCESS_KEY_SECRET
  bucket: "dvorac-android-buildtest-builds"
  skip_cleanup: true
  local_dir: app/build/outputs/apk
  region: us-east
  upload-dir: $S3_DIR